In [1]:
import numpy as np
def add1(x):
    return x + 1

print(add1(1))

2


In [7]:
b=np.ones((2,3))
b[1,:]=2
l=list(map(add1,b))
print(l)

[array([ 2.,  2.,  2.]), array([ 3.,  3.,  3.])]


In [9]:
for elements in l:
    print(elements)

[ 2.  2.  2.]
[ 3.  3.  3.]


In [11]:
type([print(el) for el in l])


[ 2.  2.  2.]
[ 3.  3.  3.]


list

In [22]:
map_O=map(add1,[1,10])

In [23]:
[print(l) in list(map_O)]

[array([ 2.,  2.,  2.]), array([ 3.,  3.,  3.])]


[False]